version: '3.1'

services:

  db:
    container_name: postgres-decisao
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'example'
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer-decisao
    image: adminer
    restart: always
    ports:
      - "8080:8080"